### ISSUE TITLE
How to use the helper function?

### ISSUE THREAD

**Issue by ppc1337** [ainsleyclark/squidge#11]
I stumbled over your plugin just this week, tried it out and love it already - at least when it comes to all the file handling.

But where I struggle with is: the helper function you provide and how to use it to have the output in the frontend / source code.

Do you have some example by hand or can provide somehow to use it in the code? I tried several things out, but as I'm not a real developer and just learn by doing and googling around, it's quite tough ...

**Comment by ainsleyclark** [comment]
Hi @ppc1337 

The helper function is designed to be used on page templates. You pass an image ID to the function and it will output a `<picture>` element. It won't be compatible with any theme builders if any case.

I hope this helps.

All the best.
