### ISSUE TITLE
How to install avifenc on Ubuntu 20.04

### ISSUE THREAD

**Issue by yonited** [ainsleyclark/squidge#15]
Hi Developer 
thank you for this awesome plugin but i find it really challenging to install avifenc on my server , i tried to search the internet without any useful guide to do that

my server distribution 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

any help would be very useful .. thank you

**Comment by yonited** [comment]
![Screenshot 2022-06-04 181533](https://user-images.githubusercontent.com/27698681/172015792-12aeb142-0022-41cd-9db3-102863f9c654.png)

![Screenshot 2022-06-04 181918](https://user-images.githubusercontent.com/27698681/172015802-9b08e6f8-005a-4d00-9c9e-50a60b7024ab.png)

**Comment by yonited** [comment]
is this package any useful .. how to download and install it manually on my server 
https://launchpad.net/ubuntu/+source/libavif/0.10.1-1build2

**Comment by ainsleyclark** [comment]
Hi @yonited 

Unforutnatley installing on avifenc on 20.04 involves quite a few steps. If you install on 21.10 it's really simple.
Please see here for more details:
https://www.reddit.com/r/AV1/comments/r1rc3h/how_can_i_install_avifenc_on_ubuntu_2004/
