### ISSUE TITLE
documentation: Update Readme (Fix Typos)

### ISSUE THREAD

**Issue by ainsleyclark** [ainsleyclark/squidge#6]
**Update Readme**

Squidge is a FREE WordPress plugin, built with developers in mind, for the compression and conversion of images using jpegoptim,
optipng, cwebp, and libavif. It’s extremely simple to use and is designed to increase PSI and boost rankings.

**Comment by rohinish404** [comment]
please tell which readme to update-
readme.md or readme.txt

**Comment by rohinish404** [comment]
i have created a pull request regarding this issue please consider it.
